version: "3.9"

services:
  client:
    container_name: client
    image: siailyadev/bushe-delivery-client:0.0.1
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  backend:
    container_name: server
    image: siailyadev/bushe-delivery-backend:0.0.1
    restart: always
    ports:
      - "3001:3000"
